Updating documentation to current state of development branch
UWDDA/antora pull request #14
Opened 2021-07-09 16:49 UTC by kgm78

This PR updates README.MD to the current state of the development branch. 

The primary changes are: 
- It adds new dependencies.
- Instructs the user to run our setup scripts rather than giving the installation commands. 
- Added configuration information relating to the conversion.sh script.
- Added Kyle Mercer as a contributor.

2021-07-16 18:36 UTC, jayczech23 commented on README.md
> +* To convert a PDF to AsciiDoc, place a file in the root folder and name it "file.pdf" then run the conversion script.
@kgm78 
Might be helpful to include name of conversion script and an example

2021-09-22 14:56 UTC, jayczech23 requested changes

2021-09-22 14:56 UTC, jayczech23 commented on README.md
>  * Hannah Pinson
Is Hannah Pinson still a maintainer?

2021-09-22 15:37 UTC, kgm78 commented
@jayczech23 Not anymore. I removed her from the maintainers section and made a new "contributors" section where she is mentioned.

2021-09-27 16:45 UTC, jayczech23 approved these changes

2021-09-27 16:47 UTC, merged